### ISSUE TITLE
Not Available status for Sense 2

### ISSUE THREAD

**Issue by guska84** [bfroggio/heart-of-frogg#20]
Hi,
Not sure if this is actually an issue, or expected, but both versions are listed as incompatible with the Sense 2

![image](https://user-images.githubusercontent.com/17737429/206869870-b5883640-d9d3-44ac-a947-ef400645662d.png)
![image](https://user-images.githubusercontent.com/17737429/206869882-c77826a8-7ce0-4b41-8d2d-3ed95da6ac5c.png)

Just wondering if there's any plans to bring it to the Sense 2, or not?

**Comment by Gikerl** [comment]
I'd be also interested in this! I'd also be happy to help if something needs testing.

**Comment by jessemillar** [comment]
It likely just needs the Sense 2 checkbox ticked in Fitbit Studio. I'll try to do this soon.

**Comment by jessemillar** [comment]
I just checked and the latest version of Heart of Frogg should support the Sense (at least the first one). It's using the latest SDK and Fitbit Studio isn't showing me a checkbox for the Sense 2 so I'd assume it's supposed to work...? I just looked at your screenshots again and they don't actually say it's unsupported, it's just warning you that it's a private app (since I haven't officially submitted it to the Fitbit store). What happens if you tap the "Install" button? 
![image](https://user-images.githubusercontent.com/4627837/208253241-9c8999db-2b36-48ee-999a-c8a17f6f1b2c.png)

**Comment by Gikerl** [comment]
For the "Sense 2", the install button is disabled. So clicking it sadly does nothing. 
What you say is true though, in the app it doesn't say anything about support, but in the browser version it says it only supports "Sense" and "Versa 3".

**Comment by jessemillar** [comment]
I just poked around the Fitbit developer forums and apparently the Sense 2 does not have support for this party apps for some reason. Maybe they'll add support later on, but for now, Heart of Frogg cannot work on a Sense 2. Sorry. https://community.fitbit.com/t5/Sense-2/Are-third-party-apps-available-on-Sense-2/td-p/5244355
